# Site settings
title: Dan Carter's Coding Blog

# Build settings
permalink: /:year/:month/:day/:title/
sass:
  sass_dir: css

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"