# Site settings
title: DC Coding

# Build settings
permalink: /:year/:month/:day/:title/
sass:
  sass_dir: css

# Plugins
plugins: [jekyll-paginate]
paginate: 3

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"